version: '3.1'

services:
  db:
    # Use a postgres image with built-in support for many useful extensions. One must select an
    # explicit version tag to resolve images for both linux/amd64 or linux/arm64, depending on the
    # value of `DOCKER_DEFAULT_PLATFORM`. see: https://github.com/supabase/postgres#extensions
    # for more info.
    image: supabase/postgres:15.1.0.124
    # start postgress with the supabase config, including sane defaults for all extensions
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: prism
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db-data:
