version: '3.1'

services:
  db:
    image: supabase/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db-data:
