apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.production.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    app: server
  name: server
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: server
status:
  loadBalancer: {}
