apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.production.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    app: xsweet
  name: xsweet
spec:
  ports:
    - name: "3004"
      port: 3004
      targetPort: 3004
  selector:
    app: xsweet
status:
  loadBalancer: {}
